# Generated by Django 2.2.2 on 2019-07-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forosh', '0003_auto_20190709_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
