# Generated by Django 2.2.2 on 2019-07-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forosh', '0004_auto_20190708_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
                ('supplier', models.CharField(max_length=200)),
                ('expiration', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
