# Generated by Django 2.2.2 on 2019-07-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forosh', '0005_auto_20190708_0921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
