# Generated by Django 2.2.2 on 2019-07-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forosh', '0006_auto_20190708_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('گربه', 'گربه'), ('سگ', 'سگ')], max_length=200),
        ),
    ]
