# Generated by Django 2.2.2 on 2019-07-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forosh', '0008_auto_20190710_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
    ]
