# Generated by Django 2.2.2 on 2019-07-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forosh', '0009_auto_20190710_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vet',
            new_name='Vets',
        ),
    ]
